version: '3'

services:
  postgres:
    image: postgres:13.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data

  memcached:
    image: memcached:1.6.9
    ports:
      - '11211:11211'
    volumes:
      - memcache-data:/data

volumes:
  postgres-data:
  redis-data:
  memcache-data:
