version: '3'

services:
  postgres:
    image: postgres:13.3
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgresql
      POSTGRES_PASSWORD: postgresql
      POSTGRES_DB: postgresql
    volumes:
      - ./docker-volumes/postgres-data:/var/lib/postgresql/data

  redis:
    image: redis:6.2
    ports:
      - '6379:6379'
    volumes:
      - ./docker-volumes/redis-data:/data

  memcached:
    image: memcached:1.6.9
    ports:
      - '11211:11211'
    volumes:
      - ./docker-volumes/memcached-data:/data
