default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: postgresql
  password: postgresql
  host: localhost
  port: 5432

development:
  <<: *default
  database: rails_api_sandbox_development

test:
  <<: *default
  database: rails_api_sandbox_test
